<?php

declare(strict_types=1);

namespace TradeAppOne\Mail\Attachables;

use Buyback\Services\Waybill;
use TradeAppOne\Utils\File\FileAutoGenerated;
use TradeAppOne\Utils\File\FileNameGenerator;

class WaybillPDF extends FileAutoGenerated
{
    public function __construct(Waybill $convertable, bool $checkPath = true)
    {
        $this->fileNameGenerator = new FileNameGenerator($convertable->date->format('d-m-Y-H-i'));
        $this->fileNameGenerator->setPrefix('romaneio-')->setExtension('pdf');

        parent::__construct($convertable, $checkPath);
    }

    public function options(): array
    {
        return [
            'as' => $this->getFilename(),
            'type' => 'application/pdf'
        ];
    }
}
